# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 544fff11a3ade4f8faddf7403aee49e7e4f6347aa58506b0a7efbe5c6a0589df995eab3b5297938fc43e50b596c503c0593a16f3dd3b8a15f389d006e670f816

test:
  secret_key_base: dece4d33982542e8a739cb7ca9bf880539756c2faf4570ad06ad8adebdbd85084d1dc74baefa0b50601a01bb85ac3ec08c6f82e370f53cfcb6366438c2d927a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
